# Generated by Django 5.1.4 on 2024-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='habit_streak',
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='completed_habits',
            field=models.IntegerField(default=0, help_text='The number of completed habits a user has'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="The user's DOB", null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, help_text='Gets the last login for the user'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='The number of points a user has, obtained from completing habits and keeping up streaks'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', help_text='The timezone the user resides in', max_length=50),
        ),
    ]
