# Generated by Django 5.1.4 on 2025-01-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_habit_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
