# Generated by Django 5.1.4 on 2025-01-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='xp_for_level',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
