# Generated by Django 5.1.4 on 2024-12-23 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitcompletion',
            name='completed_on',
        ),
        migrations.AddField(
            model_name='habitcompletion',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='The UTC datetime when the habit was completed', null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(blank=True, help_text='Optional category for organizing habits', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(help_text='Detailed description of the habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveIntegerField(default=1, help_text='How many times the habit should be completed per frequency_type'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='The time period over which the frequency is measured', max_length=8),
        ),
        migrations.AlterField(
            model_name='habit',
            name='grace_period',
            field=models.PositiveIntegerField(default=0, help_text='Number of days after the period ends where completion still counts'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(help_text='The name of the habit', max_length=255),
        ),
        migrations.AlterField(
            model_name='habit',
            name='streak',
            field=models.IntegerField(default=0, help_text='Current streak of successful completions'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(help_text='The user who owns this habit', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(help_text='The habit this completion relates to', on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about completion'),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed')], default='missed', help_text='Whether the habit was completed or missed', max_length=10),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='user',
            field=models.ForeignKey(help_text='The user who completed the habit', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', 'completed_at', 'status'], name='habits_habi_habit_i_4862ba_idx'),
        ),
    ]
