# Generated by Django 5.1.4 on 2025-01-04 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habitcompletion_completed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
