# Generated by Django 5.1.4 on 2025-01-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_created_habit_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
