# Generated by Django 5.1.4 on 2025-01-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_habitcompletion_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='total_completions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
