# Generated by Django 5.1.4 on 2025-01-19 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_items', '0002_alter_accessory_rarity'),
        ('habits', '0006_habit_total_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='accessory',
            field=models.ForeignKey(blank=True, help_text='The accessory associated with this capybara stack', null=True, on_delete=django.db.models.deletion.CASCADE, to='gacha_items.accessory'),
        ),
    ]
