# Generated by Django 5.1.4 on 2025-01-18 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the accessory', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the accessory')),
                ('image_filename', models.CharField(help_text='Relative path to the image file.', max_length=255)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', help_text='Rarity of the accessory', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of this accessory the user owns')),
                ('number_used', models.PositiveIntegerField(default=0, help_text='Number of this accessory the user has used')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accessories', to='gacha_items.accessory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accessories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'accessory')},
            },
        ),
    ]
