# Generated by Django 5.1.4 on 2025-01-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', help_text='Rarity of the accessory', max_length=50),
        ),
    ]
